name: zam_test
version: 0.2.0
description: A typed wrapper around the test package with several utilities for testing.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_test

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  test: ^1.17.8
  zam_core: ^0.5.0
