name: zam_test
version: 0.4.0
description: A typed wrapper around the test package with several utilities for testing.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_test

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  zam_core: ^0.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
